export const origamis = [
  {
    name: "Crane of Elegance",
    numberOfFolds: 45,
    originYear: 1605,
    originStory: "Created in Japan as a symbol of peace during the Edo period.",
    description:
      "A traditional crane origami design, symbolizing peace and longevity.",
    imageUrl: "https://example.com/images/crane1.jpg",
    artist: "64b81f23f6a0b502cd4567c4",
  },
  {
    name: "Lotus Bloom",
    numberOfFolds: 32,
    originYear: 1720,
    originStory:
      "Designed as a tribute to the blooming lotus flower found in sacred ponds.",
    description: "An intricate lotus design with delicate folds.",
    imageUrl: "https://example.com/images/lotus1.jpg",
    artist: "64b81f23f6a0b502cd4567c4",
  },
  {
    name: "Dragon's Flight",
    numberOfFolds: 85,
    originYear: 1802,
    originStory: "Inspired by myths of dragons soaring through the skies.",
    description: "A complex dragon origami capturing motion and grace.",
    imageUrl: "https://example.com/images/dragon1.jpg",
    artist: "64b81f23f6a0b502cd4567c4",
  },
  {
    name: "Fox of the Forest",
    numberOfFolds: 27,
    originYear: 1550,
    originStory: "Depicts a cunning fox revered in Japanese folklore.",
    description: "A playful and detailed fox design.",
    imageUrl: "https://example.com/images/fox1.jpg",
    artist: "64b81f23f6a0b502cd4567c4",
  },
  {
    name: "Koi Stream",
    numberOfFolds: 38,
    originYear: 1700,
    originStory:
      "Symbolizes strength and perseverance, much like the koi fish.",
    description: "A charming koi fish with flowing fins and scales.",
    imageUrl: "https://example.com/images/koi1.jpg",
    artist: "64b81f23f6a0b502cd4567c4",
  },
  {
    name: "Butterfly Wings",
    numberOfFolds: 18,
    originYear: 1620,
    originStory: "Inspired by the beauty of monarch butterflies in the wild.",
    description: "A simple yet elegant butterfly design.",
    imageUrl: "https://example.com/images/butterfly1.jpg",
    artist: "64b81f23f6a0b502cd4567c5",
  },
  {
    name: "Samurai Helm",
    numberOfFolds: 60,
    originYear: 1400,
    originStory: "A tribute to the courage and honor of samurai warriors.",
    description: "A bold design resembling a traditional samurai helmet.",
    imageUrl: "https://example.com/images/samurai1.jpg",
    artist: "64b81f23f6a0b502cd4567c5",
  },
  {
    name: "Swallow's Flight",
    numberOfFolds: 23,
    originYear: 1650,
    originStory: "Modeled after swallows bringing messages of spring.",
    description: "A light and airy design of a swallow in motion.",
    imageUrl: "https://example.com/images/swallow1.jpg",
    artist: "64b81f23f6a0b502cd4567c5",
  },
  {
    name: "Rising Sun",
    numberOfFolds: 50,
    originYear: 1750,
    originStory: "Represents hope and new beginnings.",
    description: "An abstract design symbolizing the sun's rays.",
    imageUrl: "https://example.com/images/sun1.jpg",
    artist: "64b81f23f6a0b502cd4567c5",
  },
  {
    name: "Tiger's Prowl",
    numberOfFolds: 70,
    originYear: 1900,
    originStory: "A celebration of the tiger's majestic and fierce presence.",
    description: "A dynamic tiger design with sharp folds.",
    imageUrl: "https://example.com/images/tiger1.jpg",
    artist: "64b81f23f6a0b502cd4567c5",
  },
  {
    name: "Cherry Blossom",
    numberOfFolds: 30,
    originYear: 1600,
    originStory: "Celebrates the fleeting beauty of cherry blossoms in spring.",
    description: "A delicate design inspired by cherry blossoms.",
    imageUrl: "https://example.com/images/cherry1.jpg",
    artist: "64b81f23f6a0b502cd4567c5",
  },
  {
    name: "Phoenix Rising",
    numberOfFolds: 88,
    originYear: 1500,
    originStory: "Inspired by legends of the phoenix rising from the ashes.",
    description: "A majestic phoenix with fiery wings.",
    imageUrl: "https://example.com/images/phoenix1.jpg",
    artist: "64b81f23f6a0b502cd4567c5",
  },
  {
    name: "Elephant's Grace",
    numberOfFolds: 54,
    originYear: 1850,
    originStory: "Pays homage to the gentle and wise nature of elephants.",
    description: "A strong and graceful elephant origami.",
    imageUrl: "https://example.com/images/elephant1.jpg",
    artist: "64b81f23f6a0b502cd4567c5",
  },
  {
    name: "Owl's Wisdom",
    numberOfFolds: 40,
    originYear: 1755,
    originStory: "Represents wisdom and insight, inspired by nocturnal owls.",
    description: "A thoughtful owl design with sharp features.",
    imageUrl: "https://example.com/images/owl1.jpg",
    artist: "64b81f23f6a0b502cd4567c5",
  },
  {
    name: "Dolphin's Leap",
    numberOfFolds: 28,
    originYear: 1950,
    originStory: "Symbolizes joy and harmony, inspired by playful dolphins.",
    description: "A sleek dolphin design in mid-leap.",
    imageUrl: "https://example.com/images/dolphin1.jpg",
    artist: "64b81f23f6a0b502cd4567c5",
  },
  {
    name: "Paper Swan",
    numberOfFolds: 25,
    originYear: 1680,
    originStory: "A classic design symbolizing purity and grace.",
    description: "A beautifully folded swan known for its simplicity.",
    imageUrl: "https://example.com/images/swan1.jpg",
    artist: "64b81f23f6a0b502cd4567c4",
  },
  {
    name: "Mountain Peak",
    numberOfFolds: 35,
    originYear: 1740,
    originStory: "Inspired by the towering mountains of Japan.",
    description: "A rugged and angular mountain design.",
    imageUrl: "https://example.com/images/mountain1.jpg",
    artist: "64b81f23f6a0b502cd4567c4",
  },
  {
    name: "The Wise Turtle",
    numberOfFolds: 42,
    originYear: 1820,
    originStory: "Represents longevity and wisdom in Japanese culture.",
    description: "A slow but intricate turtle design.",
    imageUrl: "https://example.com/images/turtle1.jpg",
    artist: "64b81f23f6a0b502cd4567c4",
  },
  {
    name: "Firefly Glow",
    numberOfFolds: 20,
    originYear: 1700,
    originStory: "Captures the magic of fireflies lighting up the night.",
    description: "A small yet elegant firefly design.",
    imageUrl: "https://example.com/images/firefly1.jpg",
    artist: "64b81f23f6a0b502cd4567c4",
  },
  {
    name: "Eagle's Soar",
    numberOfFolds: 65,
    originYear: 1800,
    originStory: "Inspired by the strength and majesty of the eagle.",
    description: "A bold design showcasing an eagle in flight.",
    imageUrl: "https://example.com/images/eagle1.jpg",
    artist: "64b81f23f6a0b502cd4567c4",
  },
  {
    name: "The Golden Carp",
    numberOfFolds: 50,
    originYear: 1690,
    originStory: "Symbolizes perseverance and transformation.",
    description: "A shimmering carp design with intricate details.",
    imageUrl: "https://example.com/images/carp1.jpg",
    artist: "64b81f23f6a0b502cd4567c6",
  },
  {
    name: "Peacock's Splendor",
    numberOfFolds: 75,
    originYear: 1775,
    originStory: "A tribute to the beauty of peacocks in full display.",
    description: "An elaborate design with spread-out feathers.",
    imageUrl: "https://example.com/images/peacock1.jpg",
    artist: "64b81f23f6a0b502cd4567c6",
  },
  {
    name: "The Samurai's Steed",
    numberOfFolds: 48,
    originYear: 1555,
    originStory: "Depicts the noble steed of a samurai warrior.",
    description: "A powerful horse design with detailed folds.",
    imageUrl: "https://example.com/images/horse1.jpg",
    artist: "64b81f23f6a0b502cd4567c6",
  },
  {
    name: "Bamboo Grove",
    numberOfFolds: 12,
    originYear: 1600,
    originStory: "Celebrates the resilience and simplicity of bamboo.",
    description: "A minimal yet meaningful bamboo stalk design.",
    imageUrl: "https://example.com/images/bamboo1.jpg",
    artist: "64b81f23f6a0b502cd4567c6",
  },
  {
    name: "The Golden Stag",
    numberOfFolds: 90,
    originYear: 1950,
    originStory: "Symbolizes grace and strength in the wild.",
    description: "A majestic stag with antlers spread wide.",
    imageUrl: "https://example.com/images/stag1.jpg",
    artist: "64b81f23f6a0b502cd4567c6",
  },
  {
    name: "The Hidden Fox",
    numberOfFolds: 37,
    originYear: 1830,
    originStory: "Represents cunning and adaptability.",
    description: "A fox with sharp features, symbolizing wit.",
    imageUrl: "https://example.com/images/fox2.jpg",
    artist: "64b81f23f6a0b502cd4567c6",
  },
  {
    name: "The Windmill",
    numberOfFolds: 18,
    originYear: 1705,
    originStory: "Celebrates the harmony between nature and technology.",
    description: "A windmill design with rotating folds.",
    imageUrl: "https://example.com/images/windmill1.jpg",
    artist: "64b81f23f6a0b502cd4567c6",
  },
  {
    name: "Crescent Moon",
    numberOfFolds: 14,
    originYear: 1630,
    originStory: "Represents mystery and dreams under the moonlight.",
    description: "A simple yet evocative crescent moon design.",
    imageUrl: "https://example.com/images/moon1.jpg",
    artist: "64b81f23f6a0b502cd4567c6",
  },
  {
    name: "The Whispering Willow",
    numberOfFolds: 30,
    originYear: 1710,
    originStory: "Symbolizes resilience and grace during storms.",
    description: "A flowing design inspired by the willow tree.",
    imageUrl: "https://example.com/images/willow1.jpg",
    artist: "64b81f23f6a0b502cd4567c6",
  },
  {
    name: "Sea Turtle's Journey",
    numberOfFolds: 43,
    originYear: 1940,
    originStory: "Pays tribute to the long voyages of sea turtles.",
    description: "A graceful sea turtle with a shell pattern.",
    imageUrl: "https://example.com/images/turtle2.jpg",
    artist: "64b81f23f6a0b502cd4567c6",
  },
  {
    name: "The Sparrow",
    numberOfFolds: 22,
    originYear: 1720,
    originStory: "A tiny bird symbolizing freedom and simplicity.",
    description: "A detailed sparrow in flight.",
    imageUrl: "https://example.com/images/sparrow1.jpg",
    artist: "64b81f23f6a0b502cd4567c7",
  },
  {
    name: "The Whispering Crane",
    numberOfFolds: 45,
    originYear: 1615,
    originStory: "Symbolizes whispers of the divine through the winds.",
    description: "An elegant crane with long neck folds.",
    imageUrl: "https://example.com/images/crane2.jpg",
    artist: "64b81f23f6a0b502cd4567c7",
  },
  {
    name: "The Mystic Deer",
    numberOfFolds: 62,
    originYear: 1500,
    originStory: "Represents mystical encounters in ancient forests.",
    description: "A deer with intricate antlers symbolizing beauty.",
    imageUrl: "https://example.com/images/deer1.jpg",
    artist: "64b81f23f6a0b502cd4567c7",
  },
  {
    name: "Rising Phoenix",
    numberOfFolds: 88,
    originYear: 1530,
    originStory: "Captures rebirth and fire of the legendary phoenix.",
    description: "A fiery design for the mythical phoenix.",
    imageUrl: "https://example.com/images/phoenix2.jpg",
    artist: "64b81f23f6a0b502cd4567c7",
  },
  {
    name: "The Brave Lion",
    numberOfFolds: 80,
    originYear: 1925,
    originStory: "Symbolizes courage and royalty.",
    description: "A fierce lion with flowing mane folds.",
    imageUrl: "https://example.com/images/lion1.jpg",
    artist: "64b81f23f6a0b502cd4567c7",
  },
];
